# Delete the .github/ folder if you're not using GitHub
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
      - qa
      - develop
  pull_request:
    branches:
      - main
      - qa
      - develop
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # Do not use pricefx-stream-maven-plugin in your production build.
    #  Instead, use pfxpackage. See .gitlab-ci.yml
    runs-on: ubuntu-latest
    environment: Develop
    env:
      PRICEFX_URL_2: ${{ secrets.PRICEFX_URL }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Printenv
        run: printenv
      - name: Install with Maven
        run: mvn clean install
      - name: Deploy with Maven
        env:
          PRICEFX_URL: ${{ secrets.PRICEFX_URL }}
          PRICEFX_PARTITION: ${{ secrets.PRICEFX_PARTITION }}
          PRICEFX_USERNAME: ${{ secrets.PRICEFX_USERNAME }}
          PRICEFX_PASSWORD: ${{ secrets.PRICEFX_PASSWORD }}
        run: mvn --batch-mode --update-snapshots -pl pricefxSrc --settings .maven/settings.xml -P pricefx-partition clean install net.pricefx.learn:pricefx-stream-maven-plugin:pricefx-deploy-all
